Repository VATSIM-UK/uk-controller-pack, pull requests merged in 2021-08, with the labels that each got.

#209 P18 CDR1 Schedule Correction
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyMaps.txt
Labels: bug

#206 Fixes #205 - Added TopSky Shawbury Triangle OCAS Region
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyMaps.txt
Labels: enhancement, awaiting-sectorfile

#214 Automatic Sector File Issue Creation
  .github/workflows/Create_Sector_file_Issue.yml
Labels: help wanted
