Repository VATSIM-UK/uk-controller-pack, pull requests merged in 2022-02, with the labels that each got.

#244 Implement 25kHz Spacing
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Birmingham/Profiles.txt
  UK/Data/Settings/Local/Bristol/Profiles.txt
  UK/Data/Settings/Local/Cardiff/Profiles.txt
  UK/Data/Settings/Local/East Midlands/Profiles.txt
  UK/Data/Settings/Local/Edinburgh/Profiles.txt
  UK/Data/Settings/Local/Exeter/Profiles.txt
  UK/Data/Settings/Local/Glasgow/Profiles.txt
  UK/Data/Settings/Local/Leeds/Profiles.txt
  UK/Data/Settings/Local/Liverpool/Profiles.txt
  UK/Data/Settings/Local/Manchester/Profiles.txt
  UK/Data/Settings/Local/Newcastle/Profiles.txt
  UK/Data/Settings/Local/Oxford/Profiles.txt
  UK/Data/Settings/Local/Solent/Profiles.txt
  UK/Data/Settings/Local/Thames/Profiles.txt
  UK/Data/Settings/TC_APP/TC_APP_Voice.txt
  UK/Data/Settings/Voice.txt
  UK/Data/Settings/Voice_Military.txt
  UK/Data/Settings/Voice_Scottish.txt
Labels: procedure-change

#246 East Midlands CTA 14 Part Time Airspace
  .github/CHANGELOG.md
  UK/Data/ASR/AC_C/C1T.asr
  UK/Data/ASR/AC_N/N1T.asr
  UK/Data/ASR/AC_S/S1T.asr
  UK/Data/Plugin/TopSky/TopSkyMaps.txt
Labels: enhancement

#253 Essex Radar -> Stansted Radar (& other EGSS position updates)
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Essex/Profiles.txt
  UK/Data/Settings/VCCS.txt
  UK/Data/Settings/VCCS_Essex.txt
  UK/Data/Settings/VCCS_Midlands.txt
  UK/Data/Settings/Voice.txt
Labels: airac

#255 Added DVR RFC Area TopSky Map
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyMaps.txt
Labels: enhancement

#247 Define New Scottish CTAs in TopSky
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyMaps.txt
Labels: airac

#263 Fixed Heathrow Voice Settings file frequencies
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Heathrow/Voice.txt
Labels: bug

#264 Updated Sector File Descriptor for new URL
  .github/CHANGELOG.md
  UK/Data/Sector/VATUK_Euroscope_files.txt
  UK/Data/Sector/VATUK_SectorFileProviderDescriptor.txt
Labels: bug

#266 Remove Old Heathrow SMR ASR
  .github/CHANGELOG.md
  UK/Data/ASR/Heathrow/Heathrow SMR 2.asr
  UK/Heathrow/Heathrow ATM.prf
Labels: enhancement
