Repository VATSIM-UK/uk-controller-pack, pull requests merged in 2023-11, with the labels that each got.

#588 Fixes #587 - 8.33 frequency updates (aerodrome)
  .github/CHANGELOG.md
  UK/Data/Settings/Voice.txt
  UK/Data/Settings/Voice_FID.txt
  UK/Data/Settings/Voice_Military.txt
  UK/Data/Settings/Voice_Scottish.txt
Labels: airac

#594 Fixes #593 - Fixed Incorrect Default Facility for EGPD & PF GND
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Aberdeen/Profiles.txt
  UK/Data/Settings/Local/Glasgow/Profiles.txt
Labels: bug

#601 vATIS: Updated frequencies to 8.33
  .github/CHANGELOG.md
  UK/vATIS/UK - AC Central.json
  UK/vATIS/UK - AC North.json
  UK/vATIS/UK - AC South.json
  UK/vATIS/UK - LON_CTR Only.json
  UK/vATIS/UK - LON_SC Only.json
  UK/vATIS/UK - PC MAN.json
  UK/vATIS/UK - Scottish AC.json
  UK/vATIS/UK - Scottish TMA.json
  UK/vATIS/UK - TC Bandbox.json
  UK/vATIS/UK - TC North+TC Mids.json
  UK/vATIS/UK - TC South.json
  UK/vATIS/UK - West.json
Labels: bug, procedure-change

#600 Fixes #599 - Correct Jersey Control Frequency
  .github/CHANGELOG.md
  UK/Data/Settings/Voice.txt
Labels: bug

#604 Fixes #602 - Add missing AGCS/AFISO frequencies
  .github/CHANGELOG.md
  UK/Data/Settings/Local/FID/Profiles.txt
  UK/Data/Settings/Voice_FID.txt
Labels: bug
