Repository VATSIM-UK/uk-controller-pack, pull requests merged in 2023-06, with the labels that each got.

#408 Fixes #405 - Scottish Lower Tags from AC to NODE
  .github/CHANGELOG.md
  UK/Data/ASR/STC/STC1.asr
  UK/Data/ASR/STC/STC2.asr
  UK/Data/ASR/STC/STC3.asr
  UK/Data/ASR/STC/STC4.asr
Labels: bug

#409 Fixes #407 - Nova Tag Fix
  .github/CHANGELOG.md
  UK/Data/Settings/Tags.txt
Labels: bug

#416 Fixes #415 - Revised BAKUR RFC Area TopSky map
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyMaps.txt
Labels: procedure-change

#414 topsky: Removed vRAF warrior exercise area activation
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyAreas.txt
Labels: procedure-change

#410 Fixes #290 - Flight information Display
  .github/CHANGELOG.md
  UK/Data/ASR/FID/FID.asr
  UK/Data/ASR/FID/Generic SMR.asr
  UK/Data/Settings/FID/FID_General.txt
  UK/Data/Settings/FID/FID_Lists.txt
  UK/Data/Settings/FID/FID_Screen.txt
  UK/Data/Settings/FID/FID_Symbology.txt
  UK/Data/Settings/Local/FID/Plugins.txt
  UK/Data/Settings/Local/FID/Profiles.txt
  UK/Data/Settings/Tags.txt
  UK/Data/Settings/Voice_FID.txt
  UK/Procedural + AFIS AG/Flight Information Display.prf
Labels: enhancement
