Repository VATSIM-UK/uk-controller-pack, pull requests merged in 2023-09, with the labels that each got.

#465 Fixes #463 - Added 8.33kHz information command to alias files
  .github/CHANGELOG.md
  UK/Data/Alias/AC_Alias.txt
  UK/Data/Alias/Heathrow_Alias.txt
Labels: enhancement

#466 Fixes #464 - 8.33 Trial (ENR Phase 1) - Transition LAC West & Clacton frequencies
  .github/CHANGELOG.md
  UK/Data/Settings/Voice.txt
Labels: procedure-change

#473 Fixes #470 - EG D001 (Trevose Head) activated by NOTAM/AUP only
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyAreas.txt
Labels: airac

#474 Fixes #471 - EG D713 (FJA South) & EG D901 (FJA North) added
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyAreas.txt
Labels: airac

#475 Fixes #472 - 8.33kHz Trial AD Phase 1
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Edinburgh/Profiles.txt
  UK/Data/Settings/Local/Essex/Stansted_Profiles.txt
  UK/Data/Settings/Local/Liverpool/Profiles.txt
  UK/Data/Settings/Voice.txt
  UK/Data/Settings/Voice_Scottish.txt
  UK/vATIS/UK - AC Central.json
  UK/vATIS/UK - AC North.json
  UK/vATIS/UK - AC South.json
  UK/vATIS/UK - LON_CTR Only.json
  UK/vATIS/UK - LON_SC Only.json
  UK/vATIS/UK - PC MAN.json
  UK/vATIS/UK - Scottish AC.json
  UK/vATIS/UK - Scottish TMA.json
  UK/vATIS/UK - TC Bandbox.json
  UK/vATIS/UK - TC North+TC Mids.json
  UK/vATIS/UK - TC South.json
Labels: procedure-change

#480 Fixes #478 - Disable show route accepting
  .github/CHANGELOG.md
  UK/Data/Settings/AC/AC_General.txt
Labels: bug

#484 Fixes #462 - Luton ATM profile to show aircraft
  .github/CHANGELOG.md
  UK/Data/ASR/Essex/Luton ATM.asr
Labels: bug

#486 vATIS: 8.33 trial phase 1 LAC frequencies
  .github/CHANGELOG.md
  UK/vATIS/UK - AC Central.json
  UK/vATIS/UK - West.json
Labels: procedure-change

#479 Fixes #469 - Update Alias file
  .github/CHANGELOG.md
  UK/Data/Alias/AC_Alias.txt
  UK/Data/Alias/Heathrow_Alias.txt
  UK/Data/Alias/demoAlias.txt
Labels: enhancement

#468 Fixes #467 - Create Channel Islands profiles, displays & settings
  .github/CHANGELOG.md
  README.md
  UK/Channel Islands/Jersey Control.prf
  UK/Data/ASR/Channel Islands/Alderney SMR.asr
  UK/Data/ASR/Channel Islands/Guernsey SMR.asr
  UK/Data/ASR/Channel Islands/Jersey Control.asr
  UK/Data/ASR/Channel Islands/Jersey SMR.asr
  UK/Data/Plugin/vParkAir.dll
  UK/Data/Settings/Local/Channel Islands/CI Radar.txt
  UK/Data/Settings/Local/Channel Islands/Plugins.txt
  UK/Data/Settings/Local/Channel Islands/Profiles.txt
  UK/Data/Settings/Tags.txt
Labels: enhancement, awaiting-sectorfile

#482 Fixes #481 - Remove Observer profiles
  .github/CHANGELOG.md
  UK/Data/ASR/Observer/Observer EGCC SMR.asr
  UK/Data/ASR/Observer/Observer EGGD SMR.asr
  UK/Data/ASR/Observer/Observer EGGP SMR.asr
  UK/Data/ASR/Observer/Observer EGPF SMR.asr
  UK/Data/ASR/Observer/Observer EGPH SMR.asr
  UK/Data/ASR/Observer/Observer EGSS SMR.asr
  UK/Data/ASR/Observer/Radar.asr
  UK/Data/Settings/Local/Observer/Settings.txt
  UK/Data/Settings/Local/Observer/Symbology.txt
  UK/Data/Settings/Local/Observer/Voice.txt
  UK/Observer/OBSPackRadar.png
  UK/Observer/OBSPackSMR.png
  UK/Observer/Observer Profile README.txt
  UK/Observer/Observer_EGCC.prf
  UK/Observer/Observer_EGGD.prf
  UK/Observer/Observer_EGGP.prf
  UK/Observer/Observer_EGPF.prf
  UK/Observer/Observer_EGPH.prf
  UK/Observer/Observer_EGSS.prf
Labels: enhancement

#488 vatis: Add EGKK/LGW custom profile
  .github/CHANGELOG.md
  UK/vATIS/EGKK - London Gatwick.json
Labels: enhancement

#490 settings: Removed old voice format and added further event splits
  .github/CHANGELOG.md
  UK/Data/Settings/Voice.txt
  UK/Data/Settings/Voice_FID.txt
  UK/Data/Settings/Voice_Military.txt
  UK/Data/Settings/Voice_Scottish.txt
Labels: enhancement, procedure-change

#487 profiles: Area profile consolidation
  .github/CHANGELOG.md
  UK/Area/London AC/Old Default/Bandbox.prf
  UK/Area/London AC/Old Default/Central.prf
  UK/Area/London AC/Old Default/North.prf
  UK/Area/London AC/Old Default/South Central.prf
  UK/Area/London AC/Old Default/South.prf
  UK/Area/London AC/Old Default/West.prf
  UK/Area/Scottish Upper/Area.prf
  UK/Data/ASR/PX_AC/AC1I.asr
  UK/Data/ASR/PX_AC/AC2I.asr
  UK/Data/ASR/PX_AC/AC3I.asr
  UK/Data/ASR/PX_AC/AC4I.asr
  UK/Data/Settings/AC/ACI_Symbology.txt
Labels: enhancement

#491 settings: Equipment in ICAO format
  .github/CHANGELOG.md
  UK/Data/Settings/AC/AC_General.txt
  UK/Data/Settings/ATM/ATM_General.txt
  UK/Data/Settings/LTC/LTC_General.txt
  UK/Data/Settings/Local/Military/General.txt
  UK/Data/Settings/Local/Scottish/PX_TC_Profiles.txt
  UK/Data/Settings/MPC/MPC_General.txt
  UK/Data/Settings/STC/STC_General.txt
  UK/Data/Settings/Sc_APP/Sc_APP_General.txt
  UK/Data/Settings/TC_APP/TC_APP_General.txt
  UK/Data/Settings/TC_APP/TC_APP_General_5A.txt
Labels: enhancement

#493 tags: update ac tags
  .github/CHANGELOG.md
  UK/Data/Settings/Tags.txt
Labels: enhancement

#495 Minor fix to 833 alias
  UK/Data/Alias/AC_Alias.txt
Labels: bug

#505 Fixes #504 - Fix ATIS frequencies in Essex Profiles
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Essex/Essex_Profiles.txt
Labels: bug

#503 Fixes #502 - Correct EGGP_GND profile type
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Liverpool/Profiles.txt
Labels: bug

#516 Fixes #513 - Reinstate squawk error indicator to TopSky Correlated A+C detailed tags
  .github/CHANGELOG.md
  UK/Data/Settings/Tags.txt
Labels: bug

#515 Fixes #508 #512 - Add initial climb info to controller information & remove quotation marks
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Aberdeen/Profiles.txt
  UK/Data/Settings/Local/Belfast/Profiles.txt
  UK/Data/Settings/Local/Birmingham/Profiles.txt
  UK/Data/Settings/Local/Bristol/Profiles.txt
  UK/Data/Settings/Local/Cardiff/Profiles.txt
  UK/Data/Settings/Local/Channel Islands/Profiles.txt
  UK/Data/Settings/Local/East Midlands/Profiles.txt
  UK/Data/Settings/Local/Edinburgh/Profiles.txt
  UK/Data/Settings/Local/Essex/Essex_Profiles.txt
  UK/Data/Settings/Local/Essex/Luton_Profiles.txt
  UK/Data/Settings/Local/Essex/Stansted_Profiles.txt
  UK/Data/Settings/Local/Exeter/Profiles.txt
  UK/Data/Settings/Local/FID/Profiles.txt
  UK/Data/Settings/Local/Gatwick/Profiles.txt
  UK/Data/Settings/Local/Glasgow/Profiles.txt
  UK/Data/Settings/Local/Heathrow/Profiles.txt
  UK/Data/Settings/Local/Leeds/Profiles.txt
  UK/Data/Settings/Local/Liverpool/Profiles.txt
  UK/Data/Settings/Local/London/AC_N_Profiles.txt
  UK/Data/Settings/Local/Manchester/Profiles.txt
  UK/Data/Settings/Local/Military/Military_Profiles.txt
  UK/Data/Settings/Local/Newcastle/Profiles.txt
  UK/Data/Settings/Local/Oxford/Profiles.txt
  UK/Data/Settings/Local/Solent/Profiles.txt
  UK/Data/Settings/Local/Southend/Profiles.txt
  UK/Data/Settings/Local/Thames/Profiles.txt
Labels: enhancement

#497 TopSky: airspace management window display on start up
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkySettings.txt
Labels: enhancement

#524 Fixes #523 - Correct EGCC_DEL Position Type
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Manchester/Profiles.txt
Labels: bug

#514 Fixes #506 - Jersey profile improvements
  .github/CHANGELOG.md
  UK/Channel Islands/Jersey Control.prf
  UK/Data/ASR/Channel Islands/Jersey Control.asr
  UK/Data/Settings/Local/Channel Islands/CI Radar.txt
Labels: enhancement

#521 Fixes #520 - Change Glasgow freetext alignment to Center Center
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Glasgow/Symbology.txt
Labels: bug

#517 Fixes #507 - TopSky: Coordination related maps display all the time
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyMaps.txt
Labels: enhancement

#544 Fixes #543 - Correct .stop alias bug
  .github/CHANGELOG.md
  UK/Data/Alias/AC_Alias.txt
  UK/Data/Alias/Heathrow_Alias.txt
Labels: bug

#550 Fixes #549 - Logon Details: password now written to profiles
  UK/LogonDetails.py
Labels: bug

#533 Fixes #510 - TopSky: Sector Indicator fixed on AC-TopSky tags
  .github/CHANGELOG.md
  UK/Data/Settings/Tags.txt
Labels: bug

#534 Fixes #522 - Flight Information Display VCCS settings
  .github/CHANGELOG.md
  UK/Procedural + AFIS AG/Flight Information Display.prf
Labels: bug

#536 Fixes #532 - TopSky: RAVSA-INLIM line display to Thames only & DST dates updates
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyAreas.txt
  UK/Data/Plugin/TopSky/TopSkyMaps.txt
Labels: bug

#542 Fixes #541 - 8.33 Trial (ENR Phase 2) - Transition all UK enroute non-event frequencies
  .github/CHANGELOG.md
  UK/Data/Settings/Voice.txt
  UK/Data/Settings/Voice_Scottish.txt
  UK/vATIS/UK - AC Central.json
  UK/vATIS/UK - AC North.json
  UK/vATIS/UK - AC South.json
  UK/vATIS/UK - LON_CTR Only.json
  UK/vATIS/UK - LON_SC Only.json
  UK/vATIS/UK - PC MAN.json
  UK/vATIS/UK - Scottish AC.json
Labels: procedure-change

#546 Fixes #545 - 8.33 Trial (AD Phase 2) - Transition EGKK frequencies
  .github/CHANGELOG.md
  UK/Data/Settings/Voice.txt
  UK/vATIS/EGKK - London Gatwick.json
Labels: procedure-change
