Repository VATSIM-UK/uk-controller-pack, pull requests merged in 2023-10, with the labels that each got.

#559 Settings: Turned off handoff request and reduced STCA
  .github/CHANGELOG.md
  UK/Data/Settings/AC/AC_General.txt
  UK/Data/Settings/FID/FID_General.txt
  UK/Data/Settings/LTC/LTC_General.txt
  UK/Data/Settings/MPC/MPC_General.txt
  UK/Data/Settings/STC/STC_General.txt
  UK/Data/Settings/TC_APP/TC_APP_General.txt
Labels: enhancement

#535 Fixes #531 - TopSky: CARD & shortcut lists default positions improved
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkySettings.txt
  UK/Data/Plugin/TopSky/TopSkySettingsLocal.txt
Labels: bug

#563 Profiles: Update LTC centrelines and CTA
  .github/CHANGELOG.md
  UK/Data/ASR/Heathrow/Heathrow Radar_1.asr
  UK/Data/ASR/Heathrow/Heathrow Radar_2.asr
  UK/Data/ASR/LTC/TC1.asr
  UK/Data/ASR/LTC/TC2.asr
  UK/Data/ASR/LTC/TCE1.asr
  UK/Data/ASR/LTC/TCE2.asr
  UK/Data/ASR/LTC/TCM1.asr
  UK/Data/ASR/LTC/TCM2.asr
  UK/Data/ASR/LTC/TCN1.asr
  UK/Data/ASR/LTC/TCN2.asr
  UK/Data/ASR/LTC/TCS1.asr
  UK/Data/ASR/LTC/TCS2.asr
Labels: awaiting-sectorfile

#566 Fixes #560 - Corrected QNH formatting in LGW vATIS profile
  .github/CHANGELOG.md
  UK/vATIS/EGKK - London Gatwick.json
Labels: bug

#573 Fixes #568 - AMA Update 2311
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyMSAW.txt
Labels: airac

#578 Fixes #575 - EGTE SMAA revised
  .github/CHANGELOG.md
  UK/Data/Plugin/TopSky/TopSkyMSAW.txt
Labels: airac

#579 Fixes #576 - Remove colons from controller ATIS lines
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Cardiff/Profiles.txt
  UK/Data/Settings/Local/Channel Islands/Profiles.txt
  UK/Data/Settings/Local/East Midlands/Profiles.txt
  UK/Data/Settings/Local/Gatwick/Profiles.txt
  UK/Data/Settings/Local/Glasgow/Profiles.txt
Labels: bug

#583 profiles: Removed colons and UNVBL -> UNAVBL
  UK/Data/Settings/Local/Essex/Essex_Profiles.txt
  UK/Data/Settings/Local/Essex/Luton_Profiles.txt
  UK/Data/Settings/Local/Essex/Stansted_Profiles.txt
  UK/Data/Settings/Local/London/AC_Profiles_No-CPDLC.txt
  UK/Data/Settings/Local/London/AC_SC_Profiles.txt
  UK/Data/Settings/Local/Scottish/PX_AC_Profiles_No-CPDLC.txt
Labels: bug

#582 settings: 8.33 Transition (ENR Phase 3) voice
  .github/CHANGELOG.md
  UK/Data/Settings/Voice.txt
  UK/Data/Settings/Voice_Scottish.txt
Labels: procedure-change
