Repository VATSIM-UK/uk-controller-pack, pull requests merged in 2024-07, with the labels that each got.

#763 Fixes #762 - Update Brize Norton (EGVN) Frequencies
  .github/CHANGELOG.md
  UK/Data/Settings/Voice_Military.txt
Labels: airac

#766 Fixes #765 - Update EGNS and EGSC frequencies
  .github/CHANGELOG.md
  UK/Data/Settings/Local/Essex/Essex_Profiles.txt
  UK/Data/Settings/Voice.txt
Labels: procedure-change

#768 Fixes #767 - vSMR Heathrow (EGLL) Geofencing Update
  .github/CHANGELOG.md
  UK/Data/ASR/AC_BB/BBG1.asr
  UK/Data/ASR/AC_S/Heathrow SMR.asr
  UK/Data/ASR/AC_SC/Heathrow SMR.asr
  UK/Data/ASR/Heathrow/Heathrow SMR.asr
  UK/Data/ASR/LTC/Heathrow SMR.asr
  UK/Data/Plugin/vSMR/aircraft-data.csv
  UK/Data/Plugin/vSMR/vSMR.dll
  UK/Data/Plugin/vSMR/vSMR_Profiles.json
Labels: enhancement
