Repository VATSIM-UK/uk-controller-pack, pull requests merged in 2024-04, with the labels that each got.

#667 Fixes #666 - Add Leeds Radar Gate to appropriate displays
  .github/CHANGELOG.md
  UK/Data/ASR/Leeds/Leeds Radar_1.asr
  UK/Data/ASR/Leeds/Leeds Radar_2.asr
  UK/Data/ASR/Leeds/Leeds Radar_3.asr
  UK/Data/ASR/Leeds/Leeds Radar_4.asr
  UK/Data/ASR/MPC/PC1.asr
  UK/Data/ASR/MPC/PC2.asr
  UK/Data/ASR/MPC/PC3.asr
  UK/Data/ASR/MPC/PC4.asr
  UK/Data/Settings/Local/Leeds/APP_Symbology.txt
Labels: enhancement

#669 Add vATIS profiles for Aerodrome Controllers
  .github/CHANGELOG.md
  UK/vATIS/ADC/Aberdeen(EGPD).json
  UK/vATIS/ADC/Belfast(EGAC & EGAA).json
  UK/vATIS/ADC/Birmingham(EGBB).json
  UK/vATIS/ADC/Channel Islands(EGJB & EGJJ).json
  UK/vATIS/ADC/Cranfield(EGTC).json
  UK/vATIS/ADC/East Midlands(EGNX).json
  UK/vATIS/ADC/Edinburgh(EGPH).json
  UK/vATIS/ADC/Essex(EGSS & EGGW & EGSC).json
  UK/vATIS/ADC/Exeter(EGTE).json
  UK/vATIS/ADC/Farnborough(EGLF).json
  UK/vATIS/ADC/Gatwick(EGKK).json
  UK/vATIS/ADC/Glasgow(EGPF).json
  UK/vATIS/ADC/Gloucestershire(EGBJ).json
  UK/vATIS/ADC/Hawarden(EGNR).json
  UK/vATIS/ADC/Heathrow(EGLL & EGWU).json
  UK/vATIS/ADC/Humberside(EGNJ).json
  UK/vATIS/ADC/Inverness(EGPE).json
  UK/vATIS/ADC/Isle of Man(EGNS).json
  UK/vATIS/ADC/Land's End(EGHC).json
  UK/vATIS/ADC/Leeds(EGNM).json
  UK/vATIS/ADC/Liverpool(EGGP).json
  UK/vATIS/ADC/Lydd(EGMD).json
  UK/vATIS/ADC/Manchester(EGCC).json
  UK/vATIS/ADC/Newquay (EGHQ).json
  UK/vATIS/ADC/Northumberland(EGNT & EGNV).json
  UK/vATIS/ADC/Norwich(EGSH).json
  UK/vATIS/ADC/Oxford(EGTK).json
  UK/vATIS/ADC/Prestwick(EGPK).json
  UK/vATIS/ADC/Redhill(EGKR).json
  UK/vATIS/ADC/Severn(EGFF & EGGD & EGSY).json
  UK/vATIS/ADC/Shoreham(EGKA).json
  UK/vATIS/ADC/Solent(EGHI & EGHH).json
  UK/vATIS/ADC/Sumburgh(EGPB).json
  UK/vATIS/ADC/Thames(EGLC & EGKB & EGMC).json
  UK/vATIS/ADC/Warton(EGNH & EGNO).json
Labels: enhancement

#678 List fixes - AC settings loading and adds RT to arrival list
  .github/CHANGELOG.md
  UK/Area/London AC/Bandbox (TopSky).prf
  UK/Area/London AC/Bandbox SMR.prf
  UK/Area/London AC/Bandbox.prf
  UK/Area/London AC/Central (TopSky).prf
  UK/Area/London AC/Central SMR.prf
  UK/Area/London AC/Central.prf
  UK/Area/London AC/North (TopSky).prf
  UK/Area/London AC/North SMR.prf
  UK/Area/London AC/North.prf
  UK/Area/London AC/South (TopSky).prf
  UK/Area/London AC/South Central (TopSky).prf
  UK/Area/London AC/South Central SMR.prf
  UK/Area/London AC/South Central.prf
  UK/Area/London AC/South SMR.prf
  UK/Area/London AC/South.prf
  UK/Area/London AC/West (TopSky).prf
  UK/Area/London AC/West SMR.prf
  UK/Area/London AC/West.prf
  UK/Area/London TC/TC Bandbox.prf
  UK/Area/London TC/TC East.prf
  UK/Area/London TC/TC Midlands.prf
  UK/Area/London TC/TC North.prf
  UK/Area/London TC/TC South.prf
  UK/Area/Manchester PC/PC Bandbox.prf
  UK/Area/Scottish Lower/Scottish Lower.prf
  UK/Area/Scottish Upper/Area (TopSky).prf
  UK/Area/Scottish Upper/Area SMR.prf
  UK/Area/Scottish Upper/Area.prf
  UK/Data/Settings/ATM/ATM_Lists.txt
  UK/Data/Settings/Lists.txt
  UK/Data/Settings/Lists_SMR.txt
  UK/Data/Settings/Lists_TopSky.txt
Labels: bug, enhancement

#590 Fixes #589 - Scottish iTEC Profile
  .github/CHANGELOG.md
  UK/Area/Scottish Upper/Area (NERC).prf
  UK/Area/Scottish Upper/Area (TopSky).prf
  UK/Area/Scottish Upper/Area (iTEC).prf
  UK/Data/ASR/PX_AC/AC1N.asr
  UK/Data/ASR/PX_AC/AC1T.asr
  UK/Data/ASR/PX_AC/AC2N.asr
  UK/Data/ASR/PX_AC/AC2T.asr
  UK/Data/ASR/PX_AC/AC3N.asr
  UK/Data/ASR/PX_AC/AC3T.asr
  UK/Data/ASR/PX_AC/AC4N.asr
  UK/Data/ASR/PX_AC/AC4T.asr
  UK/Data/Plugin/TopSky_iTEC/ICAO_Aircraft.json
  UK/Data/Plugin/TopSky_iTEC/ICAO_Aircraft.txt
  UK/Data/Plugin/TopSky_iTEC/ICAO_Airlines.txt
  UK/Data/Plugin/TopSky_iTEC/ICAO_Airports.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyAirspace.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyAreas.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyCPDLC.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyCPDLChoppieCode.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyCallsigns.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyCallsignsLocal.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyCursorArrowLeft.cur
  UK/Data/Plugin/TopSky_iTEC/TopSkyCursorArrowRight.cur
  UK/Data/Plugin/TopSky_iTEC/TopSkyCursorCross.cur
  UK/Data/Plugin/TopSky_iTEC/TopSkyCursorMove.cur
  UK/Data/Plugin/TopSky_iTEC/TopSkyCursorResize.cur
  UK/Data/Plugin/TopSky_iTEC/TopSkyCursorStop.cur
  UK/Data/Plugin/TopSky_iTEC/TopSkyMSAW.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyMaps.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyRadars.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkySSRcodes.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkySettings.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkySoundAPW.wav
  UK/Data/Plugin/TopSky_iTEC/TopSkySoundCPDLC.wav
  UK/Data/Plugin/TopSky_iTEC/TopSkySoundCoord.wav
  UK/Data/Plugin/TopSky_iTEC/TopSkySoundCoordACP.wav
  UK/Data/Plugin/TopSky_iTEC/TopSkySoundCoordRJC.wav
  UK/Data/Plugin/TopSky_iTEC/TopSkySoundSTCA.wav
  UK/Data/Plugin/TopSky_iTEC/TopSkySymbols.txt
  UK/Data/Plugin/TopSky_iTEC/TopSkyViews.txt
  UK/Data/Plugin/TopSky_iTEC/arrowleft.cur
  UK/Data/Plugin/TopSky_iTEC/arrowright.cur
  UK/Data/Plugin/TopSky_iTEC/bigcursors - for use on screens with high DPI setting/arrowleft.cur
  UK/Data/Plugin/TopSky_iTEC/bigcursors - for use on screens with high DPI setting/arrowright.cur
  UK/Data/Plugin/TopSky_iTEC/bigcursors - for use on screens with high DPI setting/cross.cur
  UK/Data/Plugin/TopSky_iTEC/bigcursors - for use on screens with high DPI setting/move.cur
  UK/Data/Plugin/TopSky_iTEC/bigcursors - for use on screens with high DPI setting/resize.cur
  UK/Data/Plugin/TopSky_iTEC/bigcursors - for use on screens with high DPI setting/stop.cur
  UK/Data/Plugin/TopSky_iTEC/cross.cur
  UK/Data/Plugin/TopSky_iTEC/move.cur
  UK/Data/Plugin/TopSky_iTEC/resize.cur
  UK/Data/Plugin/TopSky_iTEC/stop.cur
  UK/Data/Settings/AC/iTEC_Symbology.txt
  UK/Data/Settings/Tags.txt
Labels: enhancement

#677 Heathrow profile changes in advance of CTP
  .github/CHANGELOG.md
  UK/Data/ASR/Heathrow/Heathrow ATM.asr
  UK/Data/ASR/Heathrow/Heathrow SMR.asr
  UK/Data/Alias/Heathrow_Alias.txt
  UK/Data/Settings/Local/Heathrow/ATM_LL_General.txt
  UK/Data/Settings/Local/Heathrow/ATM_LL_Lists.txt
  UK/Data/Settings/Local/Heathrow/ATM_LL_Symbology.txt
  UK/Data/Settings/Local/Heathrow/ATM_Lists.txt
  UK/Data/Settings/Local/Heathrow/Profiles.txt
  UK/Data/Settings/Local/Heathrow/SMR_LL_Lists.txt
  UK/Data/Settings/Local/Heathrow/TC_APP_LL_Lists.txt
  UK/Data/Settings/Local/Heathrow/Voice.txt
  UK/Heathrow/Heathrow ATM.prf
  UK/Heathrow/Heathrow SMR.prf
  UK/Heathrow/Heathrow.prf
Labels: enhancement

#681 Fixes #679 - Heathrow profiles load Heathrow alias
  .github/CHANGELOG.md
  UK/Heathrow/Heathrow SMR.prf
  UK/Heathrow/Heathrow.prf
Labels: bug
